### ISSUE TITLE
"Configure Emacs CIDER test runner": CIDER fixes invalidate suggestion

### ISSUE THREAD

**Issue by allentiak** [practicalli/clojure-content#375]
I found out a problem with the current suggestion (see https://clojurians.zulipchat.com/#narrow/stream/151763-beginners/topic/nrepl.20on.20Emacs.3A.20clojure.20-Sdeps.3A.20FileNotFoundException/near/225029917).

(I still don't know how to fix it, though...)

This is the relevant file in this repo.
I don't know how to add a comment to it, so I'll add a pointer to it :-)
https://github.com/practicalli/clojure-content/blob/master/testing/unit-testing/configure-projects-for-tests.md

**Comment by jr0cket** [comment]
Suggest using aliases rather than specifying `-Sdeps` configuration on the command line.  Using aliases is generally more repeatable and flexible.
