### ISSUE TITLE
Rewrite hot-load documentation to match changes 

### ISSUE THREAD

**Issue by gtoast** [practicalli/clojure-content#376]
In the [alternative-tools/clojure-tools/hot-load dependencies](https://github.com/practicalli/clojure-content/blob/master/alternative-tools/clojure-tools/hot-load-dependencies.md#hot-loading-of-library-dependencies) section it refers to add-lib. [The function name has been changed to add-libs.](https://github.com/clojure/tools.deps.alpha/blob/d77476f3d5f624249462e275ae62d26da89f320b/src/main/clojure/clojure/tools/deps/alpha/repl.clj#L75) 

With your approval, I would love to create a pull request updating the documentation for this awesome feature.

**Comment by jr0cket** [comment]
Thank you for raising this issue.  I have started rewriting this page, as had not included the approach of using add-libs in the deps.edn file.

I will push this today.  If you feel more can be added to this page, then by all means start a pull request.

Thanks again.

**Comment by jr0cket** [comment]
I have pushed https://github.com/practicalli/clojure-content/commit/397da333cb187b055cb4d562ee6692a7b6e58bab to update the hotload libraries page at
https://practicalli.github.io/clojure/alternative-tools/clojure-tools/hotload-libraries.html#practicalli

Feel free to add any other examples or further explanations / corrections via a pull request.

**Comment by gtoast** [comment]
I'll review these changes tonight and either create a pull or close these tickets.

**Comment by jr0cket** [comment]
Hopefully you didnt find any further issues, so I am closing this issue.

If there is anything remaining, please open again or create a new issue.  

Thank you
